; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    lvgl/lvgl@^9.5.0
    zinggjm/GxEPD2@^1.6.9

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I src

build_src_filter =
    +<app/*>
    +<platform/common/*>
    +<platform/esp32/*>

lib_ldf_mode = deep+

board_build.arduino.memory_type = qio_opi


[env:desktop]
platform = native

lib_deps =
    lvgl/lvgl@^9.5.0

build_flags =
    -D DESKTOP
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -std=gnu++17
	-I/usr/include/SDL2
    -lSDL2

build_unflags =
    -std=gnu++11

build_src_filter =
    +<app/*>
    +<platform/common/*>
    +<platform/desktop/*>

lib_ldf_mode = deep+