; PlatformIO Project Configuration File

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    lvgl/lvgl@^9.5.0
    zinggjm/GxEPD2@^1.6.9

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -DBOARD_HAS_PSRAM
    -Wl,-Map=.pio/build/esp32s3/firmware.map
    ; -DCONFIG_BT_ENABLED=0
    ; -DCONFIG_BLUEDROID_ENABLED=0
    ; -DCONFIG_ESP_WIFI_ENABLED=0
    ; -DCONFIG_WIFI_ENABLED=0
    -DSOC_SDMMC_HOST_SUPPORTED

build_src_filter =
    +<app/*>
    +<platform/common/*>
    +<platform/esp32/*>

lib_ldf_mode = chain

board_build.arduino.memory_type = qio_opi
board_build.partitions = default.csv
board_build.arduino.partitions = default.csv
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.nobs"

[env:desktop]
platform = native

lib_deps =
    lvgl/lvgl@^9.5.0

build_flags =
    -D DESKTOP
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -std=gnu++17
	; -I/usr/include/SDL2
    ; -I /opt/homebrew/Cellar/SDL2/2.32.10/include
    ; -L /opt/homebrew/Cellar/SDL2/2.32.10/lib
    -I C:/SDL2/x86_64-w64-mingw32/include
    -L C:/SDL2/x86_64-w64-mingw32/lib
    -I C:/msys64/mingw64/include
    -L C:/msys64/mingw64/lib
    -lSDL2
    -lSDL2main
    -lcurl
    -mconsole

build_src_filter =
    +<app/*>
    +<platform/common/*>
    +<platform/desktop/*>

lib_ldf_mode = chain

extra_scripts = pre:fix_env.py
